apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/SpeedKillsx/Devops-argocd.git'
        revision: main
        directories:
          - path: 'applications/*'
            recurse: true
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/SpeedKillsx/{{path[1]}}.git'
          targetRevision: main
          path: helm-chart
          helm:
            releaseName: '{{path[1]}}'
            valueFiles:
              - $values/applications/{{path[1]}}/values.yaml
        - repoURL: 'https://github.com/SpeedKillsx/Devops-argocd.git'
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true