apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
  labels:
    app: registration-app-aws
spec:
  selector:
    app: registration-app-aws
    
  ports:
  - port: 80
    targetPort: 9001

  type: LoadBalancer
