apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
  labels:
    app: registration-app-aws
spec:
  selector:
    app: registration-app-aws
    
  ports:
  - port: 80
    targetPort: 9501
    nodePort: 30200
    protocol: TCP

  type: LoadBalancer
